// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notifications.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Notifications.Migrations
{
    [DbContext(typeof(NotificationsContext))]
    [Migration("20191130082759_Added last updated field")]
    partial class Addedlastupdatedfield
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Notifications.Models.NotificationSetting", b =>
                {
                    b.Property<string>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Daily");

                    b.Property<bool>("Mentions");

                    b.Property<int>("NotificationInterval");

                    b.Property<bool>("Replies");

                    b.Property<DateTime>("lastUpdated");

                    b.HasKey("Uid");

                    b.ToTable("NotificationSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
