// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notifications.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Notifications.Migrations
{
    [DbContext(typeof(NotificationsContext))]
    partial class NotificationsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Notifications.models.NotificationSetting", b =>
                {
                    b.Property<string>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Daily");

                    b.Property<bool>("Mentions");

                    b.Property<int>("NotificationInterval");

                    b.Property<bool>("Replies");

                    b.HasKey("Uid");

                    b.ToTable("NotificationSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
